[package]
name = "game"
version = "0.1.0"
edition = "2021"
authors = ["Maria 'hanadrizz", "Marisa", "WinterP"]

[dependencies]
bevy = "0.6.1"
rand = "0.8.5"

[workspace]
resolver = "2"

[toolchain]
channel = "nightly"
